# Generated by crate2nix 0.7.0-alpha.6 with the command:
#   "generate"
# See https://github.com/kolloch/crate2nix for more info.

{ pkgs ? import <nixpkgs> { config = {}; }
, lib ? pkgs.lib
, callPackage ? pkgs.callPackage
, stdenv ? pkgs.stdenv
, buildRustCrate ? pkgs.buildRustCrate
, fetchurl ? pkgs.fetchurl
, fetchCrate ? pkgs.fetchCrate
, defaultCrateOverrides ? pkgs.defaultCrateOverrides
, # The features to enable for the root_crate or the workspace_members.
  rootFeatures ? [ "default" ]
}:

rec {
  #
  # "public" attributes that we attempt to keep stable with new versions of crate2nix.
  #

  rootCrate = rec {
    packageId = "test-proto 0.1.0 (path+file:///home/bbigras2/tmp/test-proto)";

    # Use this attribute to refer to the derivation building your root crate package.
    # You can override the features with rootCrate.build.override { features = [ "default" "feature1" ... ]; }.
    build = buildRustCrateWithFeatures {
      features = rootFeatures;
      inherit packageId;
    };

    # Debug support which might change between releases.
    # File a bug if you depend on any for non-debug work!
    debug = debugCrate { inherit packageId; };
  };
  root_crate =
    builtins.trace "root_crate is deprecated since crate2nix 0.4. Please use rootCrate instead." rootCrate.build;
  # Refer your crate build derivation by name here.
  # You can override the features with
  # workspaceMembers."${crateName}".build.override { features = [ "default" "feature1" ... ]; }.
  workspaceMembers = {
    "test-proto" = rec {
      packageId = "test-proto 0.1.0 (path+file:///home/bbigras2/tmp/test-proto)";
      build = buildRustCrateWithFeatures {
        packageId = "test-proto 0.1.0 (path+file:///home/bbigras2/tmp/test-proto)";
        features = rootFeatures;
      };

      # Debug support which might change between releases.
      # File a bug if you depend on any for non-debug work!
      debug = debugCrate { inherit packageId; };
    };
  };
  workspace_members =
    builtins.trace
      "workspace_members is deprecated in crate2nix 0.4. Please use workspaceMembers instead."
      lib.mapAttrs (n: v: v.build) workspaceMembers;

  #
  # "private" attributes that may change in every new version of crate2nix.
  #

  # Build and dependency information for crates.
  # Many of the fields are passed one-to-one to buildRustCrate.
  #
  # Noteworthy:
  # * `crateBin = [{name = ","; path = ",";}];`: a hack to disable building the binary.
  # * `dependencies`/`buildDependencies`: similar to the corresponding fields for buildRustCrate.
  #   but with additional information which is used during dependency/feature resolution.
  # * `resolvedDependencies`: the selected default features reported by cargo - only included for debugging.
  # * `devDependencies` as of now not used by `buildRustCrate` but used to
  #   inject test dependencies into the build

  crates = {
    "c2-chacha 0.2.3 (registry+https://github.com/rust-lang/crates.io-index)" = rec {
      crateName = "c2-chacha";
      version = "0.2.3";
      edition = "2018";
      sha256 = "1fzn2n9k51b8wp4m41pkdzwlk1dbkjb6ha9rqdp4jfmzl753hhi1";
      authors = [
        "The CryptoCorrosion Contributors"
      ];
      dependencies = [
        {
          name = "ppv-lite86";
          packageId = "ppv-lite86 0.2.6 (registry+https://github.com/rust-lang/crates.io-index)";
          rename = "ppv-lite86";
          usesDefaultFeatures = false;
        }
      ];
      features = {
        "default" = [ "std" "simd" "rustcrypto_api" ];
        "rustcrypto_api" = [ "stream-cipher" "byteorder" ];
        "simd" = [ "ppv-lite86/simd" ];
        "std" = [ "ppv-lite86/std" ];
      };
      resolvedDefaultFeatures = [ "simd" "std" ];
    };
    "cfg-if 0.1.10 (registry+https://github.com/rust-lang/crates.io-index)" = rec {
      crateName = "cfg-if";
      version = "0.1.10";
      edition = "2018";
      sha256 = "08h80ihs74jcyp24cd75wwabygbbdgl05k6p5dmq8akbr78vv1a7";
      authors = [
        "Alex Crichton <alex@alexcrichton.com>"
      ];
      features = {
        "rustc-dep-of-std" = [ "core" "compiler_builtins" ];
      };
    };
    "fuchsia-cprng 0.1.1 (registry+https://github.com/rust-lang/crates.io-index)" = rec {
      crateName = "fuchsia-cprng";
      version = "0.1.1";
      edition = "2018";
      sha256 = "1fnkqrbz7ixxzsb04bsz9p0zzazanma8znfdqjvh39n14vapfvx0";
      authors = [
        "Erick Tryzelaar <etryzelaar@google.com>"
      ];
      features = {};
    };
    "getrandom 0.1.14 (registry+https://github.com/rust-lang/crates.io-index)" = rec {
      crateName = "getrandom";
      version = "0.1.14";
      edition = "2018";
      sha256 = "1sq30li71h19rhnhs1h6576ja68insajx8wvh1nn088r8pc8vg3s";
      authors = [
        "The Rand Project Developers"
      ];
      dependencies = [
        {
          name = "cfg-if";
          packageId = "cfg-if 0.1.10 (registry+https://github.com/rust-lang/crates.io-index)";
        }
        {
          name = "libc";
          packageId = "libc 0.2.66 (registry+https://github.com/rust-lang/crates.io-index)";
          usesDefaultFeatures = false;
          target = { target, features }: target."unix";
        }
        {
          name = "wasi";
          packageId = "wasi 0.9.0+wasi-snapshot-preview1 (registry+https://github.com/rust-lang/crates.io-index)";
          target = { target, features }: (target."os" == "wasi");
        }
      ];
      features = {
        "rustc-dep-of-std" = [ "compiler_builtins" "core" ];
        "test-in-browser" = [ "wasm-bindgen" ];
      };
      resolvedDefaultFeatures = [ "std" ];
    };
    "grpc-compiler 0.6.2 (registry+https://github.com/rust-lang/crates.io-index)" = rec {
      crateName = "grpc-compiler";
      version = "0.6.2";
      edition = "2015";
      # Hack to suppress building binaries
      crateBin = [ { name = ","; path = ","; } ];
      sha256 = "1cgznh0h1iw3r798mz5irx3nm112x8i91c0d1c6hmd77iv778wlh";
      authors = [
        "Stepan Koltsov <stepan.koltsov@gmail.com>"
      ];
      dependencies = [
        {
          name = "protobuf";
          packageId = "protobuf 2.8.2 (registry+https://github.com/rust-lang/crates.io-index)";
        }
        {
          name = "protobuf-codegen";
          packageId = "protobuf-codegen 2.8.2 (registry+https://github.com/rust-lang/crates.io-index)";
        }
      ];
      features = {};
    };
    "libc 0.2.66 (registry+https://github.com/rust-lang/crates.io-index)" = rec {
      crateName = "libc";
      version = "0.2.66";
      edition = "2015";
      sha256 = "0n0mwry21fxfwc063k33mvxk8xj7ia5ar8m42c9ymbam2ksb25fm";
      authors = [
        "The Rust Project Developers"
      ];
      features = {
        "default" = [ "std" ];
        "rustc-dep-of-std" = [ "align" "rustc-std-workspace-core" ];
        "use_std" = [ "std" ];
      };
      resolvedDefaultFeatures = [ "default" "std" ];
    };
    "log 0.4.8 (registry+https://github.com/rust-lang/crates.io-index)" = rec {
      crateName = "log";
      version = "0.4.8";
      edition = "2015";
      sha256 = "1xz18ixccl5c6np4linv3ypc7hpmmgpc5zzd2ymp2ssfx0mhbdhl";
      authors = [
        "The Rust Project Developers"
      ];
      dependencies = [
        {
          name = "cfg-if";
          packageId = "cfg-if 0.1.10 (registry+https://github.com/rust-lang/crates.io-index)";
        }
      ];
      features = {
        "kv_unstable_sval" = [ "kv_unstable" "sval/fmt" ];
      };
    };
    "ppv-lite86 0.2.6 (registry+https://github.com/rust-lang/crates.io-index)" = rec {
      crateName = "ppv-lite86";
      version = "0.2.6";
      edition = "2018";
      sha256 = "06zs492wbms7j5qhy58cs3976c7kyc47rx0d6fn63rgvp580njbl";
      authors = [
        "The CryptoCorrosion Contributors"
      ];
      features = {
        "default" = [ "std" "simd" ];
      };
      resolvedDefaultFeatures = [ "simd" "std" ];
    };
    "protobuf 2.8.2 (registry+https://github.com/rust-lang/crates.io-index)" = rec {
      crateName = "protobuf";
      version = "2.8.2";
      edition = "2015";
      sha256 = "0w959x31wdgfyyjpqr3kmcyql1fmdbwsbj162b8mcb67xr91hwvh";
      authors = [
        "Stepan Koltsov <stepan.koltsov@gmail.com>"
      ];
      features = {
        "with-bytes" = [ "bytes" ];
        "with-serde" = [ "serde" "serde_derive" ];
      };
    };
    "protobuf-codegen 2.8.2 (registry+https://github.com/rust-lang/crates.io-index)" = rec {
      crateName = "protobuf-codegen";
      version = "2.8.2";
      edition = "2015";
      # Hack to suppress building binaries
      crateBin = [ { name = ","; path = ","; } ];
      sha256 = "1587fbgsgs97jma13mfgqygfwlbcq57738w5khbagj9apz5vjx1x";
      authors = [
        "Stepan Koltsov <stepan.koltsov@gmail.com>"
      ];
      dependencies = [
        {
          name = "protobuf";
          packageId = "protobuf 2.8.2 (registry+https://github.com/rust-lang/crates.io-index)";
        }
      ];
      features = {};
    };
    "protoc 2.8.2 (registry+https://github.com/rust-lang/crates.io-index)" = rec {
      crateName = "protoc";
      version = "2.8.2";
      edition = "2015";
      sha256 = "1y1wsw59ywkkh79q4g0g9bvfx4lanwwr04ysjsm632j8l4751nah";
      authors = [
        "Stepan Koltsov <stepan.koltsov@gmail.com>"
      ];
      dependencies = [
        {
          name = "log";
          packageId = "log 0.4.8 (registry+https://github.com/rust-lang/crates.io-index)";
        }
      ];
      features = {};
    };
    "protoc-rust 2.8.2 (registry+https://github.com/rust-lang/crates.io-index)" = rec {
      crateName = "protoc-rust";
      version = "2.8.2";
      edition = "2015";
      sha256 = "1gr208pd0bl8p0jqyjbrccv4syxxz3hzd6b0b1d96mvwqzfm3a5y";
      authors = [
        "Stepan Koltsov <stepan.koltsov@gmail.com>"
      ];
      dependencies = [
        {
          name = "protobuf";
          packageId = "protobuf 2.8.2 (registry+https://github.com/rust-lang/crates.io-index)";
        }
        {
          name = "protobuf-codegen";
          packageId = "protobuf-codegen 2.8.2 (registry+https://github.com/rust-lang/crates.io-index)";
        }
        {
          name = "protoc";
          packageId = "protoc 2.8.2 (registry+https://github.com/rust-lang/crates.io-index)";
        }
        {
          name = "tempfile";
          packageId = "tempfile 3.1.0 (registry+https://github.com/rust-lang/crates.io-index)";
        }
      ];
      features = {};
    };
    "protoc-rust-grpc 0.6.2 (registry+https://github.com/rust-lang/crates.io-index)" = rec {
      crateName = "protoc-rust-grpc";
      version = "0.6.2";
      edition = "2015";
      sha256 = "1ml09kkygdk93x9s2pc9xr7qxair76y2i8p5w29pc19lk0vrx5bb";
      authors = [
        "Stepan Koltsov <stepan.koltsov@gmail.com>"
      ];
      dependencies = [
        {
          name = "grpc-compiler";
          packageId = "grpc-compiler 0.6.2 (registry+https://github.com/rust-lang/crates.io-index)";
        }
        {
          name = "protobuf";
          packageId = "protobuf 2.8.2 (registry+https://github.com/rust-lang/crates.io-index)";
        }
        {
          name = "protoc";
          packageId = "protoc 2.8.2 (registry+https://github.com/rust-lang/crates.io-index)";
        }
        {
          name = "protoc-rust";
          packageId = "protoc-rust 2.8.2 (registry+https://github.com/rust-lang/crates.io-index)";
        }
        {
          name = "tempdir";
          packageId = "tempdir 0.3.7 (registry+https://github.com/rust-lang/crates.io-index)";
        }
      ];
      features = {};
    };
    "rand 0.4.6 (registry+https://github.com/rust-lang/crates.io-index)" = rec {
      crateName = "rand";
      version = "0.4.6";
      edition = "2015";
      sha256 = "14qjfv3gggzhnma20k0sc1jf8y6pplsaq7n1j9ls5c8kf2wl0a2m";
      authors = [
        "The Rust Project Developers"
      ];
      dependencies = [
        {
          name = "fuchsia-cprng";
          packageId = "fuchsia-cprng 0.1.1 (registry+https://github.com/rust-lang/crates.io-index)";
          target = { target, features }: (target."os" == "fuchsia");
        }
        {
          name = "libc";
          packageId = "libc 0.2.66 (registry+https://github.com/rust-lang/crates.io-index)";
          optional = true;
          target = { target, features }: target."unix";
        }
        {
          name = "rand_core";
          packageId = "rand_core 0.3.1 (registry+https://github.com/rust-lang/crates.io-index)";
          usesDefaultFeatures = false;
          target = { target, features }: (target."env" == "sgx");
        }
        {
          name = "rdrand";
          packageId = "rdrand 0.4.0 (registry+https://github.com/rust-lang/crates.io-index)";
          target = { target, features }: (target."env" == "sgx");
        }
        {
          name = "winapi";
          packageId = "winapi 0.3.8 (registry+https://github.com/rust-lang/crates.io-index)";
          target = { target, features }: target."windows";
          features = [ "minwindef" "ntsecapi" "profileapi" "winnt" ];
        }
      ];
      features = {
        "default" = [ "std" ];
        "nightly" = [ "i128_support" ];
        "std" = [ "libc" ];
      };
      resolvedDefaultFeatures = [ "default" "libc" "std" ];
    };
    "rand 0.7.3 (registry+https://github.com/rust-lang/crates.io-index)" = rec {
      crateName = "rand";
      version = "0.7.3";
      edition = "2018";
      sha256 = "00sdaimkbz491qgi6qxkv582yivl32m2jd401kzbn94vsiwicsva";
      authors = [
        "The Rand Project Developers"
        "The Rust Project Developers"
      ];
      dependencies = [
        {
          name = "getrandom";
          packageId = "getrandom 0.1.14 (registry+https://github.com/rust-lang/crates.io-index)";
          rename = "getrandom_package";
          optional = true;
        }
        {
          name = "libc";
          packageId = "libc 0.2.66 (registry+https://github.com/rust-lang/crates.io-index)";
          optional = true;
          usesDefaultFeatures = false;
          target = { target, features }: target."unix";
        }
        {
          name = "rand_chacha";
          packageId = "rand_chacha 0.2.1 (registry+https://github.com/rust-lang/crates.io-index)";
          usesDefaultFeatures = false;
          target = { target, features }: (!(target."os" == "emscripten"));
        }
        {
          name = "rand_core";
          packageId = "rand_core 0.5.1 (registry+https://github.com/rust-lang/crates.io-index)";
        }
        {
          name = "rand_hc";
          packageId = "rand_hc 0.2.0 (registry+https://github.com/rust-lang/crates.io-index)";
          target = { target, features }: (target."os" == "emscripten");
        }
      ];
      devDependencies = [
        {
          name = "rand_hc";
          packageId = "rand_hc 0.2.0 (registry+https://github.com/rust-lang/crates.io-index)";
        }
      ];
      features = {
        "alloc" = [ "rand_core/alloc" ];
        "default" = [ "std" ];
        "getrandom" = [ "getrandom_package" "rand_core/getrandom" ];
        "nightly" = [ "simd_support" ];
        "simd_support" = [ "packed_simd" ];
        "small_rng" = [ "rand_pcg" ];
        "std" = [ "rand_core/std" "rand_chacha/std" "alloc" "getrandom" "libc" ];
        "stdweb" = [ "getrandom_package/stdweb" ];
        "wasm-bindgen" = [ "getrandom_package/wasm-bindgen" ];
      };
      resolvedDefaultFeatures = [ "alloc" "default" "getrandom" "getrandom_package" "libc" "std" ];
    };
    "rand_chacha 0.2.1 (registry+https://github.com/rust-lang/crates.io-index)" = rec {
      crateName = "rand_chacha";
      version = "0.2.1";
      edition = "2018";
      sha256 = "0lv8imzzl4h2glm6sjj8mkvasgi8jym23ya48dakyln7m06sk8h3";
      authors = [
        "The Rand Project Developers"
        "The Rust Project Developers"
        "The CryptoCorrosion Contributors"
      ];
      dependencies = [
        {
          name = "c2-chacha";
          packageId = "c2-chacha 0.2.3 (registry+https://github.com/rust-lang/crates.io-index)";
          usesDefaultFeatures = false;
          features = [ "simd" ];
        }
        {
          name = "rand_core";
          packageId = "rand_core 0.5.1 (registry+https://github.com/rust-lang/crates.io-index)";
        }
      ];
      features = {
        "default" = [ "std" "simd" ];
        "std" = [ "c2-chacha/std" ];
      };
      resolvedDefaultFeatures = [ "std" ];
    };
    "rand_core 0.3.1 (registry+https://github.com/rust-lang/crates.io-index)" = rec {
      crateName = "rand_core";
      version = "0.3.1";
      edition = "2015";
      sha256 = "0jzdgszfa4bliigiy4hi66k7fs3gfwi2qxn8vik84ph77fwdwvvs";
      authors = [
        "The Rand Project Developers"
        "The Rust Project Developers"
      ];
      dependencies = [
        {
          name = "rand_core";
          packageId = "rand_core 0.4.2 (registry+https://github.com/rust-lang/crates.io-index)";
        }
      ];
      features = {
        "alloc" = [ "rand_core/alloc" ];
        "default" = [ "std" ];
        "serde1" = [ "rand_core/serde1" ];
        "std" = [ "rand_core/std" ];
      };
    };
    "rand_core 0.4.2 (registry+https://github.com/rust-lang/crates.io-index)" = rec {
      crateName = "rand_core";
      version = "0.4.2";
      edition = "2015";
      sha256 = "1p09ynysrq1vcdlmcqnapq4qakl2yd1ng3kxh3qscpx09k2a6cww";
      authors = [
        "The Rand Project Developers"
        "The Rust Project Developers"
      ];
      features = {
        "serde1" = [ "serde" "serde_derive" ];
        "std" = [ "alloc" ];
      };
    };
    "rand_core 0.5.1 (registry+https://github.com/rust-lang/crates.io-index)" = rec {
      crateName = "rand_core";
      version = "0.5.1";
      edition = "2018";
      sha256 = "06bdvx08v3rkz451cm7z59xwwqn1rkfh6v9ay77b14f8dwlybgch";
      authors = [
        "The Rand Project Developers"
        "The Rust Project Developers"
      ];
      dependencies = [
        {
          name = "getrandom";
          packageId = "getrandom 0.1.14 (registry+https://github.com/rust-lang/crates.io-index)";
          optional = true;
        }
      ];
      features = {
        "serde1" = [ "serde" ];
        "std" = [ "alloc" "getrandom" "getrandom/std" ];
      };
      resolvedDefaultFeatures = [ "alloc" "getrandom" "std" ];
    };
    "rand_hc 0.2.0 (registry+https://github.com/rust-lang/crates.io-index)" = rec {
      crateName = "rand_hc";
      version = "0.2.0";
      edition = "2018";
      sha256 = "0g31sqwpmsirdlwr0svnacr4dbqyz339im4ssl9738cjgfpjjcfa";
      authors = [
        "The Rand Project Developers"
      ];
      dependencies = [
        {
          name = "rand_core";
          packageId = "rand_core 0.5.1 (registry+https://github.com/rust-lang/crates.io-index)";
        }
      ];
      features = {};
    };
    "rdrand 0.4.0 (registry+https://github.com/rust-lang/crates.io-index)" = rec {
      crateName = "rdrand";
      version = "0.4.0";
      edition = "2015";
      sha256 = "1cjq0kwx1bk7jx3kzyciiish5gqsj7620dm43dc52sr8fzmm9037";
      authors = [
        "Simonas Kazlauskas <rdrand@kazlauskas.me>"
      ];
      dependencies = [
        {
          name = "rand_core";
          packageId = "rand_core 0.3.1 (registry+https://github.com/rust-lang/crates.io-index)";
          usesDefaultFeatures = false;
        }
      ];
      features = {
        "default" = [ "std" ];
      };
      resolvedDefaultFeatures = [ "default" "std" ];
    };
    "redox_syscall 0.1.56 (registry+https://github.com/rust-lang/crates.io-index)" = rec {
      crateName = "redox_syscall";
      version = "0.1.56";
      edition = "2015";
      sha256 = "110y7dyfm2vci4x5vk7gr0q551dvp31npl99fnsx2fb17wzwcf94";
      libName = "syscall";
      authors = [
        "Jeremy Soller <jackpot51@gmail.com>"
      ];
      features = {};
    };
    "remove_dir_all 0.5.2 (registry+https://github.com/rust-lang/crates.io-index)" = rec {
      crateName = "remove_dir_all";
      version = "0.5.2";
      edition = "2015";
      sha256 = "0bkrlyg26mgizpiy1yb2hhpgscxcag8r5fnckqsvk25608vzm0sa";
      authors = [
        "Aaronepower <theaaronepower@gmail.com>"
      ];
      dependencies = [
        {
          name = "winapi";
          packageId = "winapi 0.3.8 (registry+https://github.com/rust-lang/crates.io-index)";
          target = { target, features }: target."windows";
          features = [ "std" "errhandlingapi" "winerror" "fileapi" "winbase" ];
        }
      ];
      features = {};
    };
    "tempdir 0.3.7 (registry+https://github.com/rust-lang/crates.io-index)" = rec {
      crateName = "tempdir";
      version = "0.3.7";
      edition = "2015";
      sha256 = "1n5n86zxpgd85y0mswrp5cfdisizq2rv3la906g6ipyc03xvbwhm";
      authors = [
        "The Rust Project Developers"
      ];
      dependencies = [
        {
          name = "rand";
          packageId = "rand 0.4.6 (registry+https://github.com/rust-lang/crates.io-index)";
        }
        {
          name = "remove_dir_all";
          packageId = "remove_dir_all 0.5.2 (registry+https://github.com/rust-lang/crates.io-index)";
        }
      ];
      features = {};
    };
    "tempfile 3.1.0 (registry+https://github.com/rust-lang/crates.io-index)" = rec {
      crateName = "tempfile";
      version = "3.1.0";
      edition = "2018";
      sha256 = "1a9cfdqw70n7bcnkx05aih9xdba8lqazmqlkjpkmn2la6gcj8vks";
      authors = [
        "Steven Allen <steven@stebalien.com>"
        "The Rust Project Developers"
        "Ashley Mannix <ashleymannix@live.com.au>"
        "Jason White <jasonaw0@gmail.com>"
      ];
      dependencies = [
        {
          name = "cfg-if";
          packageId = "cfg-if 0.1.10 (registry+https://github.com/rust-lang/crates.io-index)";
        }
        {
          name = "libc";
          packageId = "libc 0.2.66 (registry+https://github.com/rust-lang/crates.io-index)";
          target = { target, features }: target."unix";
        }
        {
          name = "rand";
          packageId = "rand 0.7.3 (registry+https://github.com/rust-lang/crates.io-index)";
        }
        {
          name = "redox_syscall";
          packageId = "redox_syscall 0.1.56 (registry+https://github.com/rust-lang/crates.io-index)";
          target = { target, features }: (target."os" == "redox");
        }
        {
          name = "remove_dir_all";
          packageId = "remove_dir_all 0.5.2 (registry+https://github.com/rust-lang/crates.io-index)";
        }
        {
          name = "winapi";
          packageId = "winapi 0.3.8 (registry+https://github.com/rust-lang/crates.io-index)";
          target = { target, features }: target."windows";
          features = [ "fileapi" "handleapi" "winbase" ];
        }
      ];
      features = {};
    };
    "test-proto 0.1.0 (path+file:///home/bbigras2/tmp/test-proto)" = rec {
      crateName = "test-proto";
      version = "0.1.0";
      edition = "2018";
      crateBin = [
        { name = "test-proto"; path = "src/main.rs"; }
      ];
      src = (builtins.filterSource sourceFilter ./.);
      authors = [
        "Bruno Bigras <bigras.bruno@gmail.com>"
      ];
      buildDependencies = [
        {
          name = "protoc-rust-grpc";
          packageId = "protoc-rust-grpc 0.6.2 (registry+https://github.com/rust-lang/crates.io-index)";
        }
      ];
      features = {};
    };
    "wasi 0.9.0+wasi-snapshot-preview1 (registry+https://github.com/rust-lang/crates.io-index)" = rec {
      crateName = "wasi";
      version = "0.9.0+wasi-snapshot-preview1";
      edition = "2018";
      sha256 = "06g5v3vrdapfzvfq662cij7v8a1flwr2my45nnncdv2galrdzkfc";
      authors = [
        "The Cranelift Project Developers"
      ];
      features = {
        "default" = [ "std" ];
        "rustc-dep-of-std" = [ "compiler_builtins" "core" "rustc-std-workspace-alloc" ];
      };
      resolvedDefaultFeatures = [ "default" "std" ];
    };
    "winapi 0.3.8 (registry+https://github.com/rust-lang/crates.io-index)" = rec {
      crateName = "winapi";
      version = "0.3.8";
      edition = "2015";
      sha256 = "1ii9j9lzrhwri0902652awifzx9fpayimbp6hfhhc296xcg0k4w0";
      authors = [
        "Peter Atashian <retep998@gmail.com>"
      ];
      dependencies = [
        {
          name = "winapi-i686-pc-windows-gnu";
          packageId = "winapi-i686-pc-windows-gnu 0.4.0 (registry+https://github.com/rust-lang/crates.io-index)";
          target = { target, features }: (stdenv.hostPlatform.config == "i686-pc-windows-gnu");
        }
        {
          name = "winapi-x86_64-pc-windows-gnu";
          packageId = "winapi-x86_64-pc-windows-gnu 0.4.0 (registry+https://github.com/rust-lang/crates.io-index)";
          target = { target, features }: (stdenv.hostPlatform.config == "x86_64-pc-windows-gnu");
        }
      ];
      features = {
        "debug" = [ "impl-debug" ];
      };
      resolvedDefaultFeatures = [ "errhandlingapi" "fileapi" "handleapi" "minwindef" "ntsecapi" "profileapi" "std" "winbase" "winerror" "winnt" ];
    };
    "winapi-i686-pc-windows-gnu 0.4.0 (registry+https://github.com/rust-lang/crates.io-index)" = rec {
      crateName = "winapi-i686-pc-windows-gnu";
      version = "0.4.0";
      edition = "2015";
      sha256 = "1dmpa6mvcvzz16zg6d5vrfy4bxgg541wxrcip7cnshi06v38ffxc";
      authors = [
        "Peter Atashian <retep998@gmail.com>"
      ];
      features = {};
    };
    "winapi-x86_64-pc-windows-gnu 0.4.0 (registry+https://github.com/rust-lang/crates.io-index)" = rec {
      crateName = "winapi-x86_64-pc-windows-gnu";
      version = "0.4.0";
      edition = "2015";
      sha256 = "0gqq64czqb64kskjryj8isp62m2sgvx25yyj3kpc2myh85w24bki";
      authors = [
        "Peter Atashian <retep998@gmail.com>"
      ];
      features = {};
    };
  };

  #
  # crate2nix/default.nix (excerpt start)
  # 

  # Target (platform) data for conditional dependencies.
  # This corresponds roughly to what buildRustCrate is setting.
  defaultTarget = {
    unix = true;
    windows = false;
    fuchsia = true;
    test = false;

    # This doesn't appear to be officially documented anywhere yet.
    # See https://github.com/rust-lang-nursery/rust-forge/issues/101.
    os = if stdenv.hostPlatform.isDarwin
    then "macos"
    else stdenv.hostPlatform.parsed.kernel.name;
    arch = stdenv.hostPlatform.parsed.cpu.name;
    family = "unix";
    env = "gnu";
    endian = if stdenv.hostPlatform.parsed.cpu.significantByte.name == "littleEndian" then "little" else "big";
    pointer_width = toString stdenv.hostPlatform.parsed.cpu.bits;
    vendor = stdenv.hostPlatform.parsed.vendor.name;
    debug_assertions = false;
  };

  /* Filters common temp files and build files */
  # TODO(pkolloch): Substitute with gitignore filter
  sourceFilter = name: type:
    let
      baseName = builtins.baseNameOf (builtins.toString name);
    in
      ! (
        # Filter out git
        baseName == ".gitignore" || (type == "directory" && baseName == ".git") || # Filter out build results
        (
          type == "directory" && (
            baseName == "target" || baseName == "_site" || baseName == ".sass-cache" || baseName == ".jekyll-metadata" || baseName == "build-artifacts"
          )
        ) || # Filter out nix-build result symlinks
        (type == "symlink" && lib.hasPrefix "result" baseName) || # Filter out IDE config
        (
          type == "directory" && (
            baseName == ".idea" || baseName == ".vscode"
          )
        ) || lib.hasSuffix ".iml" baseName || # Filter out nix build files
        # lib.hasSuffix ".nix" baseName ||
        baseName == "Cargo.nix" || # Filter out editor backup / swap files.
        lib.hasSuffix "~" baseName || builtins.match "^\\.sw[a-z]$$" baseName != null || builtins.match "^\\..*\\.sw[a-z]$$" baseName != null || lib.hasSuffix ".tmp" baseName || lib.hasSuffix ".bak" baseName || baseName == "tests.nix"
      );

  /* Returns a crate which depends on successful test execution of crate given as the second argument */
  crateWithTest = crate: testCrate: testCrateFlags:
    let
      # override the `crate` so that it will build and execute tests instead of
      # building the actual lib and bin targets We just have to pass `--test`
      # to rustc and it will do the right thing.  We execute the tests and copy
      # their log and the test executables to $out for later inspection.
      test = let
        drv = testCrate.override (
          _: {
            buildTests = true;
          }
        );
      in
        pkgs.runCommand "run-tests-${testCrate.name}" {
          inherit testCrateFlags;
        } ''
          set -e
          for file in ${drv}/tests/*; do
            echo "Executing test $file" | tee -a $out
            $file -- "$testCrateFlags" 2>&1 | tee -a $out
          done
        '';
    in
      crate.overrideAttrs (
        old: {
          checkPhase = ''
            test -e ${test}
          '';
          passthru = (old.passthru or {}) // {
            inherit test;
          };
        }
      );

  /* A restricted overridable version of  buildRustCrateWithFeaturesImpl. */
  buildRustCrateWithFeatures =
    { packageId
    , features ? rootFeatures
    , crateOverrides ? defaultCrateOverrides
    , buildRustCrateFunc ? buildRustCrate
    , runTests ? false
    , testCrateFlags ? []
    }:
      lib.makeOverridable
        (
          { features, crateOverrides, runTests, testCrateFlags }:
            let
              builtRustCrates = builtRustCratesWithFeatures {
                inherit packageId features crateOverrides buildRustCrateFunc;
                runTests = false;
              };
              builtTestRustCrates = builtRustCratesWithFeatures {
                inherit packageId features crateOverrides buildRustCrateFunc;
                runTests = true;
              };
              drv = builtRustCrates.${packageId};
              testDrv = builtTestRustCrates.${packageId};
            in
              if runTests then crateWithTest drv testDrv testCrateFlags else drv
        )
        { inherit features crateOverrides runTests testCrateFlags; };

  /* Returns a buildRustCrate derivation for the given packageId and features. */
  builtRustCratesWithFeatures =
    { packageId
    , features
    , crateConfigs ? crates
    , crateOverrides
    , buildRustCrateFunc
    , runTests
    , target ? defaultTarget
    } @ args:
      assert (builtins.isAttrs crateConfigs);
      assert (builtins.isString packageId);
      assert (builtins.isList features);
      assert (builtins.isAttrs target);
      assert (builtins.isBool runTests);

      let
        rootPackageId = packageId;
        mergedFeatures = mergePackageFeatures (
          args // {
            inherit rootPackageId;
            target = target // { test = runTests; };
          }
        );

        buildByPackageId = packageId: buildByPackageIdImpl packageId;

        # Memoize built packages so that reappearing packages are only built once.
        builtByPackageId =
          lib.mapAttrs (packageId: value: buildByPackageId packageId) crateConfigs;

        buildByPackageIdImpl = packageId:
          let
            features = mergedFeatures."${packageId}" or [];
            crateConfig' = crateConfigs."${packageId}";
            crateConfig = builtins.removeAttrs crateConfig' [ "resolvedDefaultFeatures" "devDependencies" ];
            devDependencies = lib.optionals (runTests && packageId == rootPackageId) (crateConfig'.devDependencies or []);
            dependencies =
              dependencyDerivations {
                inherit builtByPackageId features target;
                dependencies =
                  (crateConfig.dependencies or [])
                  ++ devDependencies;
              };
            buildDependencies =
              dependencyDerivations {
                inherit builtByPackageId features target;
                dependencies = crateConfig.buildDependencies or [];
              };

            dependenciesWithRenames =
              lib.filter (d: d ? "rename") (
                (crateConfig.buildDependencies or [])
                ++ (crateConfig.dependencies or [])
                ++ devDependencies
              );

            crateRenames =
              builtins.listToAttrs (map (d: { name = d.name; value = d.rename; }) dependenciesWithRenames);
          in
            buildRustCrateFunc (
              crateConfig // {
                src = crateConfig.src or (
                  pkgs.fetchurl {
                    name = "${crateConfig.crateName}-${crateConfig.version}.tar.gz";
                    url = "https://crates.io/api/v1/crates/${crateConfig.crateName}/${crateConfig.version}/download";
                    sha256 = crateConfig.sha256;
                  }
                );
                inherit features dependencies buildDependencies crateRenames;
              }
            );
      in
        builtByPackageId;

  /* Returns the actual derivations for the given dependencies. */
  dependencyDerivations =
    { builtByPackageId
    , features
    , dependencies
    , target
    }:
      assert (builtins.isAttrs builtByPackageId);
      assert (builtins.isList features);
      assert (builtins.isList dependencies);
      assert (builtins.isAttrs target);

      let
        enabledDependencies = filterEnabledDependencies { inherit dependencies features target; };
        depDerivation = dependency: builtByPackageId.${dependency.packageId};
      in
        map depDerivation enabledDependencies;

  sanitizeForJson = val:
    if builtins.isAttrs val
    then lib.mapAttrs (n: v: sanitizeForJson v) val
    else if builtins.isList val
    then builtins.map sanitizeForJson val
    else if builtins.isFunction val
    then "function"
    else val;

  debugCrate = { packageId, target }:
    assert (builtins.isString packageId);

    rec {
      # The built tree as passed to buildRustCrate.
      buildTree = buildRustCrateWithFeatures {
        buildRustCrateFunc = lib.id;
        inherit packageId;
      };
      sanitizedBuildTree = sanitizeForJson buildTree;
      dependencyTree = sanitizeForJson (
        buildRustCrateWithFeatures {
          buildRustCrateFunc = crate: {
            "01_crateName" = crate.crateName or false;
            "02_features" = crate.features or [];
            "03_dependencies" = crate.dependencies or [];
          };
          inherit packageId;
        }
      );
      mergedPackageFeatures = mergePackageFeatures { inherit packageId target; features = rootFeatures; };
      diffedDefaultPackageFeatures = diffDefaultPackageFeatures { inherit packageId;  features = rootFeatures; };
    };

  /* Returns differences between cargo default features and crate2nix default features.
   *
   * This is useful for verifying the feature resolution in crate2nix.
   */
  diffDefaultPackageFeatures =
    { crateConfigs ? crates
    , packageId
    , target
    }:
      assert (builtins.isAttrs crateConfigs);

      let
        prefixValues = prefix: lib.mapAttrs (n: v: { "${prefix}" = v; });
        mergedFeatures =
          prefixValues
            "crate2nix"
            (mergePackageFeatures { inherit crateConfigs packageId target; features = [ "default" ]; });
        configs = prefixValues "cargo" crateConfigs;
        combined = lib.foldAttrs (a: b: a // b) {} [ mergedFeatures configs ];
        onlyInCargo = builtins.attrNames (lib.filterAttrs (n: v: !(v ? "crate2nix") && (v ? "cargo")) combined);
        onlyInCrate2Nix = builtins.attrNames (lib.filterAttrs (n: v: (v ? "crate2nix") && !(v ? "cargo")) combined);
        differentFeatures = lib.filterAttrs
          (
            n: v:
              (v ? "crate2nix")
              && (v ? "cargo")
              && (v.crate2nix.features or []) != (v."cargo".resolved_default_features or [])
          )
          combined;
      in
        builtins.toJSON { inherit onlyInCargo onlyInCrate2Nix differentFeatures; };

  /* Returns the feature configuration by package id for the given input crate.

     Returns a { packageId, features } attribute set for every package needed for building the
     package for the given packageId with the given features.

     Returns multiple, potentially conflicting attribute sets for dependencies that are reachable
     by multiple paths in the dependency tree.
  */

  mergePackageFeatures =
    { crateConfigs ? crates
    , packageId
    , rootPackageId
    , features ? rootFeatures
    , dependencyPath ? [ crates.${packageId}.crateName ]
    , featuresByPackageId ? {}
    , target
    , runTests
    , ...
    } @ args:
      assert (builtins.isAttrs crateConfigs);
      assert (builtins.isString packageId);
      assert (builtins.isList features);
      assert (builtins.isAttrs featuresByPackageId);

      let
        crateConfig = crateConfigs."${packageId}" or (builtins.throw "Package not found: ${packageId}");
        expandedFeatures = expandFeatures (crateConfig.features or {}) features;

        depWithResolvedFeatures = dependency:
          let
            packageId = dependency.packageId;
            features = dependencyFeatures expandedFeatures dependency;
          in
            { inherit packageId features; };

        resolveDependencies = cache: path: dependencies:
          assert (builtins.isAttrs cache);
          assert (builtins.isList dependencies);

          let
            enabledDependencies = filterEnabledDependencies {
              inherit dependencies target;
              features = expandedFeatures;
            };
            directDependencies = map depWithResolvedFeatures enabledDependencies;
            foldOverCache = op: lib.foldl op cache directDependencies;
          in
            foldOverCache
              (
                cache: { packageId, features }:
                  let
                    cacheFeatures = cache.${packageId} or [];
                    combinedFeatures = sortedUnique (cacheFeatures ++ features);
                  in
                    if cache ? ${packageId} && cache.${packageId} == combinedFeatures
                    then cache
                    else mergePackageFeatures {
                      # This is purely for debugging.
                      dependencyPath = dependencyPath ++ [ path crateConfigs.${packageId}.crateName ];
                      features = combinedFeatures;
                      featuresByPackageId = cache;
                      inherit crateConfigs packageId target runTests rootPackageId;
                    }
              );

        cacheWithSelf =
          let
            cacheFeatures = featuresByPackageId.${packageId} or [];
            combinedFeatures = sortedUnique (cacheFeatures ++ expandedFeatures);
          in
            featuresByPackageId // {
              ${packageId} = combinedFeatures;
            };

        cacheWithDependencies =
          resolveDependencies cacheWithSelf "dep" (
            crateConfig.dependencies or []
            ++ lib.optionals (runTests && packageId == rootPackageId) (crateConfig.devDependencies or [])
          );
        cacheWithAll =
          resolveDependencies cacheWithDependencies "build" (crateConfig.buildDependencies or []);

      in
        cacheWithAll;

  /* Returns the enabled dependencies given the enabled features. */
  filterEnabledDependencies = { dependencies, features, target }:
    assert (builtins.isList dependencies);
    assert (builtins.isList features);
    assert (builtins.isAttrs target);

    lib.filter
      (
        dep:
          let
            targetFunc = dep.target or (features: true);
          in
            targetFunc { inherit features target; }
            && (!(dep.optional or false) || builtins.any (doesFeatureEnableDependency dep) features)
      )
      dependencies;

  /* Returns whether the given feature should enable the given dependency. */
  doesFeatureEnableDependency = { name, rename ? null, ... }: feature:
    let
      prefix = "${name}/";
      len = builtins.stringLength prefix;
      startsWithPrefix = builtins.substring 0 len feature == prefix;
    in
      feature == name || (rename != null && rename == feature) || startsWithPrefix;

  /* Returns the expanded features for the given inputFeatures by applying the rules in featureMap.

     featureMap is an attribute set which maps feature names to lists of further feature names to enable in case this
     feature is selected.
  */
  expandFeatures = featureMap: inputFeatures:
    assert (builtins.isAttrs featureMap);
    assert (builtins.isList inputFeatures);

    let
      expandFeature = feature:
        assert (builtins.isString feature);
        [ feature ] ++ (expandFeatures featureMap (featureMap."${feature}" or []));
      outFeatures = builtins.concatMap expandFeature inputFeatures;
    in
      sortedUnique outFeatures;

  /*
   * Returns the actual dependencies for the given dependency.
   *
   * features: The features of the crate that refers this dependency.
   */
  dependencyFeatures = features: dependency:
    assert (builtins.isList features);
    assert (builtins.isAttrs dependency);

    let
      defaultOrNil = if dependency.usesDefaultFeatures or true
      then [ "default" ]
      else [];
      explicitFeatures = dependency.features or [];
      additionalDependencyFeatures =
        let
          dependencyPrefix = dependency.name + "/";
          dependencyFeatures =
            builtins.filter (f: lib.hasPrefix dependencyPrefix f) features;
        in
          builtins.map (lib.removePrefix dependencyPrefix) dependencyFeatures;
    in
      defaultOrNil ++ explicitFeatures ++ additionalDependencyFeatures;

  /* Sorts and removes duplicates from a list of strings. */
  sortedUnique = features:
    assert (builtins.isList features);
    assert (builtins.all builtins.isString features);

    let
      outFeaturesSet = lib.foldl (set: feature: set // { "${feature}" = 1; }) {} features;
      outFeaturesUnique = builtins.attrNames outFeaturesSet;
    in
      builtins.sort (a: b: a < b) outFeaturesUnique;

  #
  # crate2nix/default.nix (excerpt end)
  # 

}
