[package]
name = "test-proto"
version = "0.1.0"
authors = ["Bruno Bigras <bigras.bruno@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
protoc-rust-grpc = "0.6"